### ISSUE TITLE
Problem in executing

### ISSUE THREAD

**Issue by josephrj** [tgjeon/TensorFlow-Tutorials-for-Time-Series#10]
WARNING:tensorflow:From C:\Users\JOSEPH\Anaconda3\envs\tensorflow-cpu\lib\site-packages\tensorflow\contrib\learn\python\learn\monitors.py:269: BaseMonitor.__init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.

WARNING:tensorflow:From C:\Users\JOSEPH\Anaconda3\envs\tensorflow-cpu\lib\site-packages\tensorflow\contrib\learn\python\learn\monitors.py:269: BaseMonitor.__init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-9b67778a78d9> in <module>()
     55                                                       early_stopping_rounds=1000)
     56 
---> 57 regressor.fit(X['train'], y['train'],monitors=[validation_monitor],logdir=LOG_DIR)
     58 
     59  # self.assertTrue(hook.loss_collection)

TypeError: fit() got an unexpected keyword argument 'monitors'

**Comment by pusj** [comment]
@josephrj ,

Which ver. of TF are you using?

Regards
Staffan

**Comment by josephrj** [comment]
@pusj, 
1.3.0 version

**Comment by josephrj** [comment]
TypeError: fit() got an unexpected keyword argument 'monitors'
please fix this error

**Comment by pusj** [comment]
@josephrj ,

This is most likely due to that monitors has been deprecated, @tgjeon is working on updating the code for TF 1.2, until this is complete, could you test the version of the code I have worked on to see if you get the same error? https://github.com/pusj/LSTM-Time-Series-Analysis-using-Tensorflow 

_I would work with TF 1.3 but the last time I installed this version it threw the pywrap error for the GPU version. TF 1.2 with GPU and TF 1.3 without GPU both works fine...(I havent tried upgrading cuDNN from 5.1 to 6.0 but I'll try this when I get some spare time)_

**Comment by josephrj** [comment]
@pusj 
AttributeError: module 'tensorflow.contrib.learn' has no attribute 'TensorFlowEstimator'
is there any other attribute in replacement for this in tensorflow 1.3

**Comment by josephrj** [comment]
@pusj 
AttributeError: module 'tensorflow' has no attribute 'histogram_summary'
is there any other attribute in replacement for this in tensorflow 1.3

**Comment by pusj** [comment]
@josephrj; See comment above; I'm not working in TF 1.3, I'm using TF 1.2.
